In [3]:
import numpy as np

In [27]:
a1 = np.array([[1,2,3,4,5],[7,8,9,10,11]], np.float16)
a2 = np.zeros((2,3))
a3 = np.empty((2,3,2))
a4 = np.ones((2,3,4))

In [40]:
a5 = np.array([np.arange(1,10),range(10,20)])

In [60]:
a5 = np.zeros((2,5),np.int)

In [62]:
a5[1] = np.arange(6,11)

In [84]:
a1 = np.array([[1,2,3],[2,2,2],[3,4,5]])
a0 = np.eye(3)
a0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [128]:
a0

array([[1000.,    0.,    2.],
       [   0.,    1.,    0.],
       [   0.,    0.,    1.]])

In [140]:
a0[:,:1]

array([[1000.],
       [   0.],
       [  10.]])

In [165]:
data = np.random.randn(7,4)
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [170]:
data[names!='Bob']

array([[-0.2709616 ,  0.96288921, -0.23988425,  0.46322267],
       [-2.05062808, -0.6867059 ,  0.64076887, -0.48455773],
       [ 1.08121516,  0.40172361,  1.47427551,  1.18727109],
       [-1.19684576,  2.0239539 , -0.61326544,  0.07733534],
       [ 0.21579002, -0.77678373,  2.51527574,  0.73861349]])

In [162]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [173]:
data

array([[-0.47648619,  0.32974072, -0.9659135 , -0.55181618],
       [-0.2709616 ,  0.96288921, -0.23988425,  0.46322267],
       [-2.05062808, -0.6867059 ,  0.64076887, -0.48455773],
       [ 0.17880269,  0.59734633, -2.02625528, -0.74290404],
       [ 1.08121516,  0.40172361,  1.47427551,  1.18727109],
       [-1.19684576,  2.0239539 , -0.61326544,  0.07733534],
       [ 0.21579002, -0.77678373,  2.51527574,  0.73861349]])

In [175]:
data

array([[-0.47648619,  0.        , -0.9659135 , -0.55181618],
       [-0.2709616 ,  0.        , -0.23988425,  0.        ],
       [-2.05062808, -0.6867059 ,  0.        , -0.48455773],
       [ 0.        ,  0.        , -2.02625528, -0.74290404],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.19684576,  0.        , -0.61326544,  0.        ],
       [ 0.        , -0.77678373,  0.        ,  0.        ]])